spring.application.name=ticketmanagement
spring.data.mongodb.uri=mongodb+srv://mominaman2207_db_user:2207@ticketsystem.u5t2gup.mongodb.net/?appName=ticketsystem
spring.data.mongodb.database=ticket_management

server.port=8080