spring.application.name=ticketmanagement
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DB}

# JWT Configuration
jwt.secret=THIS_IS_A_SECRET_KEY_FOR_TICKET_MANAGEMENT_SYSTEM_2026
jwt.expiration=3600000

server.port=${PORT:8080}
# Max file upload size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB